# Generated by Django 4.1.7 on 2023-03-16 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('symbol', models.CharField(max_length=150, unique=True, verbose_name='Символьный код')),
                ('price', models.FloatField(verbose_name='Цена за единицу в USD')),
                ('percent_change_24h', models.FloatField(verbose_name='Изменение цены в процентах')),
                ('volume', models.FloatField(verbose_name='Объем торгов')),
            ],
            options={
                'verbose_name': 'Криптовалюта',
                'verbose_name_plural': 'Криптовалюты',
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptocurrencies.cryptocurrency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранные',
            },
        ),
    ]
