# Generated by Django 4.1.7 on 2023-03-16 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='percent_change_24h',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='volume',
        ),
    ]
